### ISSUE TITLE
Could not find function "hash_encode_salt"

### ISSUE THREAD

**Issue by rkgrep** [iCyberon/pg_hashids#13]
Do you have any idea why this might happen?

```
ERROR:  could not find function "hash_encode_salt" in file "/usr/lib/postgresql/9.6/lib/pg_hashids.so"
```

Here is the build process: https://github.com/viblo-asia/docker-postgres/blob/master/9.6/Dockerfile

**Comment by iCyberon** [comment]
@rkgrep oh, looks like you forgot to create extension in Postgres `CREATE EXTENSION pg_hashids;`. Just open a psql session an issue the command.

**Comment by iCyberon** [comment]
If you're still having the issue, feel free to open the issue.
