### ISSUE TITLE
Using With Docker and Hasura

### ISSUE THREAD

**Issue by alteredorange** [iCyberon/pg_hashids#24]
Any direction on how to get this working with Docker (and specifically the Heroku image)?  It seems like I should be adding this to the `docker-compose.yaml`, but I'm quite stuck. Any help would be greatly appreciated, thanks!

**Comment by alteredorange** [comment]
Got this sorted, just needed to install with dockerfile.  Any chance you can bundle 1.3 as a release so I can grab the tar file with wget?  Thanks!!

**Comment by iCyberon** [comment]
@alteredorange yup, will do it
