### ISSUE TITLE
Error creating the pg_hashids extension

### ISSUE THREAD

**Issue by Yash-Hiran** [iCyberon/pg_hashids#28]
After following the steps from README
when I run the command ```CREATE extension pg_hashids```. I get the below error

`could not open extension control file "/usr/share/postgresql/13/extension/pg_hashids.control" 
`
how can this be fixed?

**Comment by rotten** [comment]
Several things might have gone wrong here.  Firstly, confirm the file exists and is readable by the user your postgresql database is using.  Did you build pg_hashids for postgresql 13?

**Comment by Yash-Hiran** [comment]
Oh, fixed the issue! Thanks a lot!
