### ISSUE TITLE
How to make extension in Windows

### ISSUE THREAD

**Issue by wilsontamarozzi** [iCyberon/pg_hashids#5]
Hello,

Sorry about my English.

I would like to know how to build the extension using Windows. I installed MingW to compile but it does not recognize the Make command.

Could you give me more instructions to do this on Windows?

Grateful

**Comment by iCyberon** [comment]
@wilsontamarozzi Unfortunately, I don't have experience in compiling for windows. You can try this [method](https://blog.2ndquadrant.com/compiling-postgresql-extensions-visual-studio-windows/). Let me know if you have any questions, I am happy to assist you

**Comment by kilgarenone** [comment]
I'm struggling installing makefile on windows 10... Tried it in WSL but nothing works...

What's the alternative that achieve similar thing like `hashids`?
