### ISSUE TITLE
Several PostgreSQL versions

### ISSUE THREAD

**Issue by hmartinet** [iCyberon/pg_hashids#6]
Hello,

How to choose the pg version for make/make install ? It's deployed in 9.3 but not in 9.6 (I have both and I want to use it in 9.6).

Thanks

[edit] Ok I succeeded to deploy if by removing one or the other pg sources. But this is not very user friendly.

**Comment by iCyberon** [comment]
@hmartinet Glad you've find a way. You could also change `PG_CONFIG` in makefile to point to the version you want. Doing `which pg_config` might help. Let me know if you have any questions
