### ISSUE TITLE
This is great but not usable in hosted environments

### ISSUE THREAD

**Issue by timuckun** [iCyberon/pg_hashids#9]
Would it be possible to write a pure PL-PGSQL version of this code?

**Comment by iCyberon** [comment]
@timuckun, it should be possible to create in pgsql, but I don't have any plans to rewrite in the near future. Anyway, what's the most important/needed feature you would like to see in pgsql version (besides hashing of course)?
P.S. There is also [plv8 implementation](https://blog.abevoelker.com/2017-01-03/generating-youtube-like-ids-in-postgres-using-plv8-and-hashids/), though I think you know about that.

**Comment by timuckun** [comment]
For me the appeal is to be able to use on Amazon RDS. I do know about the PlV8 version but there seems to be some aberration there because I can't decode the hashids encoded with plv8 with ruby.

**Comment by tim-phillips** [comment]
Of note, the plv8 implementation won't work on RDS as the master user does not have permission to set parameter `plv8.start_proc`.

```sql
ALTER DATABASE db_name SET plv8.start_proc = 'load_hashids';
```

`ERROR:  permission denied to set parameter "plv8.start_proc"`

**Comment by timuckun** [comment]
I was working on a plpgsql version of hashids but I put it aside. Maybe I
should pick it up again. I was almost done with it.

**Comment by ashok-sc** [comment]
Is this still not working on AWS RDS?

**Comment by andreystepanov** [comment]
I have implemented PL/pgSQL version which you can use in hosted environments such as AWS RDS: 

https://github.com/andreystepanov/hashids.sql
